---
title: "Lab 00 - Hello IDS!"
author: "Chenxi Li"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Alice", "Bob", 
           "Chloe", "David"),
  github_username = c("mcgregors-garden", "alice01", "bob02", 
                      "chloe03", "david04"), 
  colour = c("powderblue", "pink", "green", 
             "purple", "orange"),
  hobby = c("Hopping", "running", "hiking", 
            "reading", "gaming"),
  favourite_number = c(2, 3, 4, 5, 6)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

the plot shows each team member's favourire number by GitHub username, with the bars filled using their favourite colours.

